name: nginx-ingress
version: 0.8.0
appVersion: 1.10.0
apiVersion: v1
kubeVersion: ">= 1.14.0-0"
description: NGINX Ingress Controller
icon: https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v1.10.0/deployments/helm-chart/chart-icon.png
home: https://github.com/nginxinc/kubernetes-ingress
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/v1.10.0/deployments/helm-chart
keywords:
  - ingress
  - nginx
maintainers:
  - name: nginxinc
    email: kubernetes@nginx.com
annotations:
  catalog.cattle.io/rancher-version: "< 2.6.3"
