apiVersion: v1
appVersion: 1.3.0
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
icon: file://../hpedev.png
maintainers:
- name: datamattsson
  email: hpe-containers-dev@hpe.com
sources:
- https://scod.hpedev.io/csi_driver
name: hpe-csi-driver
home: https://hpe.com/storage/containers
version: 1.3.0
keywords:
  - HPE
  - Storage
  - StorageClass
  - CentOS
  - Ubuntu
  - RHEL
annotations:
  catalog.cattle.io/rancher-version: "< 2.6.3"
