apiVersion: v2
appVersion: "v2.1.0"
description: Cloud Native storage for containers
name: storageos-operator
version: 0.4.0
keywords:
- storage
- block-storage
- volume
- operator
home: https://storageos.com
icon: https://docs.storageos.com/images/logo-helm.svg
sources:
- https://github.com/storageos
maintainers:
- name: croomes
  email: simon.croome@storageos.com
- name: darkowlzz
  email: sunny.gogoi@storageos.com
