apiVersion: v1
appVersion: 1.4.0
description: A Helm chart for installing the HPE CSI Driver for Kubernetes
home: https://hpe.com/storage/containers
icon: https://raw.githubusercontent.com/hpe-storage/co-deployments/master/docs/assets/hpedev.png
keywords:
- HPE
- Storage
- StorageClass
- CentOS
- Ubuntu
- RHEL
maintainers:
- email: hpe-containers-dev@hpe.com
  name: raunakkumar
name: hpe-csi-driver
sources:
- https://scod.hpedev.io/csi_driver
version: 1.4.2
annotations:
  catalog.cattle.io/rancher-version: "< 2.6.3"
